import Head from 'next/head'
import MainContent from '@/components/MainContent'
import MoonJpg from "@/assets/moon.jpg";
import UploadImage from '@/components/UploadImage/UploadImage'
import {getNasaPhotos, Photo, mapToPhoto} from '@/nasa';


export interface HomeProps {
  photos: Array<Photo>;
}


export default function Home({photos}: HomeProps) {
  return (
    <>
      <Head>
        <title> NASA </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{
        display: "flex",
      }}>
        <MainContent photos={photos}/>
      </main>
      
      <section
        style={{
          backgroundImage: `url(${MoonJpg.src})`,
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat", 
          alignItems: "center",
          justifyContent: "center",
          height: 500,
        }}
      >
        <UploadImage />
      </section>
    </>
  )
}




export const getServerSideProps = async () => {
  let photos: Array<Photo> = [];

  try {
    const res = await getNasaPhotos();
    photos = res.map(mapToPhoto);
  } catch (e) {
    console.error(e);
  }

  if (photos.length < 4) {
    const emptyPhotos = Array(4 - photos.length).fill(null)
      .map((empty, i) => ({ id: String(i), src: "", title: ""}));
    photos = [...photos, ...emptyPhotos];
  }

  return {
    props: {
      photos,
    },
  };
};